language: node_js              # 指定环境及其node_js版本
node_js: 
  - lts/*

cache:                         # 缓存，提高下次构建的效率
  npm: false
  directories:
    - node_modules

install:                       # 安装阶段（详细的各阶段顺序，请查询 Travis-CI 相关文档）
  - npm install hexo-cli -g
  - npm install

script:                        # 执行构建阶段
  - hexo clean                 # hexo 的清理命令
  - hexo generate              # hexo 的生成（构建）命令，即最核心的生成静态文件过程

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "qinlzhu"
  - git config user.email "qinlzhu@outlook.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${Trcl_Deployment_Token}@${GH_REF}" master:gh-pages

branches:
  only:
    - master                   # 只监测 master 分支

env:                           # 设置全局变量
  global:                      # 注意此处的链接必须是 http 的链接，ssh 的会报错
    - GH_REF: github.com/qLzhu/trcl-deployer-git.git